console_title_template = '{{ .Shell }} in {{ .Folder }}'
version = 3
final_space = true

[upgrade]
  source = 'cdn'
  interval = '168h'
  auto = false
  notice = false

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    type = 'path'
    template = '{{ .Path }} '
    #style = 'diamond'
    #trailing_diamond = ""
    #background = 'blue'
    #style = 'powerline'
    #leading_powerline_symbol = ""
    #powerline_symbol = ""
    style = 'plain'
    background = 'transparent'
    foreground = 'blue'

    [blocks.segments.properties]
      style = 'full'

    [[blocks.segments]]
      type = 'git'
      style = 'plain'
      foreground = '#6c6c6c'
      background = 'transparent'
      template = '{{ .HEAD }}{{if or (.Working.Changed) (.Staging.Changed)}}*{{end}}{{if gt .Behind 0}}⇣{{.Behind}}{{end}}{{if gt .Ahead 0}}⇡{{end}} ' 
     [blocks.segments.properties]
        branch_icon = ''
        fetch_status = true

    [[blocks.segments]]
      type = 'text'
      style = 'plain'
      template = '❯'
      foreground = 'green'

[transient_prompt]
background = "transparent"
foreground = "#ffffff"
template = "{{ .Shell }}> "

[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'
  [[blocks.segments]]
    template = '{{.FormattedMs}}'
    type = 'executiontime'
    style = 'plain'
    background = 'orange'
    foreground = 'black'
    [blocks.segments.properties]
      threshold = 500

# Used for multi line commands
[secondary_prompt]
  template = "❯❯ "
  background = "transparent"
  foreground = "green"
